Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/24
      Tags:
        - { Key: Name, Value: Sample VPC }
  PrivateSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.0.0/25
      AvailabilityZone: ap-northeast-1a
      Tags:
        - { Key: Name, Value: Sample Private A }
  PrivateSubnetC:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.0.128/25
      AvailabilityZone: ap-northeast-1c
      Tags:
        - { Key: Name, Value: Sample Private C }
  LambdaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SecurityGroup for Lambda Functions
      VpcId: !Ref VPC
      Tags:
        - Key: "Name"
          Value: "LambdaSecurityGroup"
  AuroraSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SecurityGroup for Aurora
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: 10.0.0.0/24
      Tags:
        - Key: "Name"
          Value: "AuroraSecurityGroup"
    DependsOn: VPC
